version: "3"
services:
  front:
    build: ./front
    image: sentency-front:0.1
    ports: 
    - 3000:3000
    depends_on: 
      - api
    volumes:
    - ./front:/usr/src/app

  api:
    build: ./api
    image: sentency-api:0.3
    working_dir: /app
    volumes: 
    - ./api:/app
    environment: 
    - AIO_PORT=80
    expose:
    - 80
