version: "3"
services:
  front:
    build: ./front
    image: sentency-front:0.1
    ports: 
    - "3000:80"
    depends_on: 
      - api

  api:
    build: ./api
    image: sentency-api:0.2
    working_dir: /app
    volumes: 
    - ./api:/app
    ports:
    - 8080:8080